services:
  mycar:
    container_name: mycar-php
    build:
      context: .
      dockerfile: .docker/Dockerfile  # Ensure this path is correct
    image: mycar
    restart: always
    ports:
      - 80:80
    volumes:
      - ./car-app:/var/www/html
      - ./car-app/storage:/var/www/html/storage
      - ./car-app/bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      APP_ENV: local
      APP_DEBUG: true

  database:
    container_name: mycar-db
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'

  database-client:
    container_name: mycar-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 54320:8080
